# 工作流名称
name: Build and Push Docker Images

# 触发工作流的条件，这里设置为手动触发，并且仅在 master 分支上可触发
on:
  workflow_dispatch:
    branches:
      - master

# 定义工作流中的作业
jobs:
  build:
    # 指定作业运行的环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest

    # 定义作业的步骤
    steps:
      # 步骤 1：检出代码仓库
      - name: Checkout repository
        # 使用 actions/checkout 动作将代码仓库检出到工作目录
        uses: actions/checkout@v3

      # 步骤 2：设置 Docker Buildx
      - name: Set up Docker Buildx
        # 使用 docker/setup-buildx-action 动作来配置 Docker Buildx，以便支持多平台构建
        uses: docker/setup-buildx-action@v2

      # 步骤 3：登录到 Docker Hub
      - name: Log in to Docker Hub
        # 使用 docker/login-action 动作进行 Docker Hub 登录
        uses: docker/login-action@v2
        with:
          # 从 GitHub 仓库的 secrets 中获取 Docker Hub 的用户名
          username: ${{ secrets.DOCKER_USERNAME }}
          # 从 GitHub 仓库的 secrets 中获取 Docker Hub 的密码
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 步骤 4：从 version.json 文件中获取版本号
      - name: Get version from version.json
        run: |
          # 使用 PowerShell 读取 version.json 文件并解析其中的 version 字段
          $version = (Get-Content version.json | ConvertFrom-Json).version
          # 将获取到的版本号写入环境变量，以便后续步骤使用
          echo "version=$version" >> $env:GITHUB_ENV
        # 指定使用 PowerShell 脚本执行该步骤
        shell: pwsh

      # 步骤 5：构建并推送 Docker 镜像
      - name: Build and push Docker image
        # 使用 docker/build-push-action 动作来构建并推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          # 指定构建上下文为当前目录
          context: .
          # 开启推送功能，将构建好的镜像推送到 Docker Hub
          push: true
          # 指定要构建和推送的镜像标签
          tags: |
            # 最新版本标签
            guovern/iptv-api:latest
            # 具体版本号标签，版本号从环境变量中获取
            guovern/iptv-api:${{ env.version }}
          # 指定要构建的目标平台，包括 x86_64、ARM64 和 ARM v7 架构
          platforms: linux/amd64,linux/arm64,linux/arm/v7
